name: ride_driver
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  image_picker: ^1.1.2
  getwidget: ^7.0.0
  dio: ^5.4.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: any
  flutter_map: any
  latlong2: any
  geolocator: any
  geocoding: any
  flutter_svg: any
  google_fonts: any
  awesome_snackbar_content: any
  form_validator: ^2.0.1
  intl: ^0.19.0  
  permission_handler: ^11.3.1
  open_route_service: ^1.2.5
  iconoir_flutter: ^6.4.0
  location_picker_flutter_map: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/